

### [dev]
#
staticUploadPath=/app/tomcat8/tomcat-dglg-9098/webapps/upload
staticUrlPrefix=https://dglg.tongshike.cn/upload/

# 
jdbcUrl=jdbc:mysql://119.3.253.124:3306/dglg?autoReconnect=true&allowMultiQueries=true&useSSL=true&useUnicode=true&characterEncoding=utf8
jdbcUsername=ulearningdb
jdbcPassword=ulearning_2015




#### [prod]
##
#staticUploadPath=
#staticUrlPrefix=https://172.31.135.81/upload/
#
## 
#jdbcUrl=jdbc:mysql://127.0.0.1:3306/dglg?autoReconnect=true&allowMultiQueries=true&useSSL=true&useUnicode=true&characterEncoding=utf8
#jdbcUsername=wenhua
#jdbcPassword=wenhua_20210915


